SERVER_IP = "0.0.0.0"
SERVER_PORT = 5555
BUFFER_SIZE = 4096

GRID_WIDTH = 24
GRID_HEIGHT = 12
PLAYER_SPEED = 1
GAME_TIMER_SECONDS = 180

GAME_STATE_START_SCREEN = "start_screen"
GAME_STATE_PLAYING = "playing"
GAME_STATE_END_SCREEN = "end_screen"
