SERVER_IP = "127.0.0.1"
SERVER_PORT = 5555

BUFFER_SIZE = 4096

GRID_WIDTH = 24
GRID_HEIGHT = 12

PLAYER_SPEED = 0.1
GAME_TIMER_SECONDS = 300

GAME_STATE_START_SCREEN = "start_screen"
GAME_STATE_PLAYING = "playing"
GAME_STATE_END_SCREEN = "end_screen"

STATION_SIZE = 2
STATION_TYPE_FUSION = "fusion"
STATION_TYPE_ENTER = "enter"

ORDER_SPAWN_INTERVAL_MIN = 5
ORDER_SPAWN_INTERVAL_MAX = 15